version: '3.8'

services:
  symbiomes-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symbiomes-builder-temp
    
    # Map the container's /app/dist folder to a new local folder named 'build_output'
    volumes:
      - ./build_output:/app/dist 
    