version: '3.8'

services:
  symbiomes-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symbiomes-builder-temp
    restart: always
    ports:
      # Map the container's port 80 to port 5173 on the host VPS.
      - "5173:80"
    